### ISSUE TITLE
[FEAT] 교육탭, 설정탭 유저 정보 로직 구현

### ISSUE THREAD

**Issue by visionWWW** [CPR2U/CPR2U-Android#24]
## 🔥 Issue

 교육탭, 설정탭 유저 정보 로직, 서버 구현

## 📌 Todo

- [x] [GET] 유저정보 조회 서버
- [x] 교육탭 유저정보 로직
- [x] 설정탭 유저정보 로직
