### ISSUE TITLE
[FIX] 전체 로직 실시간 수정

### ISSUE THREAD

**Issue by visionWWW** [CPR2U/CPR2U-Android#34]
## 🔥 Issue

변경된 뷰, 로직, 서버 수정
Todo 하나씩 추가

## 📌 Todo

- [ ]  주소 피커
- [ ] 주소 설정 서버
- [x] 호출 카운트다운 타이머 고치기
- [x] 프로필 프로그래스 바 수정
- [x] 호출 전체 주소 텍스트 영역 수정
- [ ] 호출 출동 15초마다 접근하는 사람 업데이트 서버
