### ISSUE TITLE
[FEAT] 로그인/회원가입 로직

### ISSUE THREAD

**Issue by visionWWW** [CPR2U/CPR2U-Android#4]
## 🔥 Issue

로그인/회원가입 로직 작성

## 📌 Todo

- [x] 로그인 화면 1 - 전화번호 빈칸일 경우 버튼 비활성화
- [x] 로그인 화면 2 - 인증번호 빈칸일 경우 버튼 비활성화
- [x] 회원가입 화면 1 - 닉네임 유효검사
