### ISSUE TITLE
[UI] 피드백 반영 UI 수정

### ISSUE THREAD

**Issue by visionWWW** [CPR2U/CPR2U-Android#52]
## 🔥 Issue

피드백 반영 UI 수정

## 📌 Todo

- [x]  학습 메인 탭 UI
- [x]  학습 메인 탭 로직 추가
- [x]  각종 Dialog 수정
    - [x]  퀴즈 통과, 탈락 Dialog
    - [x]  CPR 자격증 취득 Dialog
    - [x]  환자에게 도착 시 뜨는 Dialog
- [x]  호출 전 메인 화면 UI 수정
- [x]  호출 전 메인 화면 UI 로직 추가
- [x]  출동화면 Bottom Sheet UI 수정
- [x]  프로필 UI
