### ISSUE TITLE
[FIX] 출동 로직 변경

### ISSUE THREAD

**Issue by visionWWW** [CPR2U/CPR2U-Android#54]
## 🔥 Issue

출동 로직 변경

## 📌 Todo

- [x]  출동버튼 누르면 → Dialog 생성
- [x]  1초마다 거리 측정
- [x]  70미터 이내 도착 시 출동 완료 처리
- [x]  출동완료 Dialog 생성
- [x]  신고 화면 연결 수정
