### ISSUE TITLE
[FIX] 자세 연습 로직 수정

### ISSUE THREAD

**Issue by visionWWW** [CPR2U/CPR2U-Android#56]
## 🔥 Issue

자세 연습 로직 수정

## 📌 Todo

- [x] 자세 연습 ring 변경
- [x] 3초가 끝난후 자세를 한번 측정하는 문제 해결
- [x] 판단 점수 수정
